### PR TITLE
Refactor & update readme

### PR DESCRIPTION
**Pull request by radeva**
- docs: update readme & contribution guide
- refactor: align with nativescript-plugin-seed structure
- chore: use nativescript-ui-listview instead of nativescript-pro-ui

### CODE REVIEW

**Review by lini — CHANGES_REQUESTED** [review]
`src/package-lock.json` - do we need this file?
`src/platforms/android/include.gradle` - we definitely need this file and its missing/not copied when moving src

**Comment by VladimirAmiorkov** [comment]
@lini Resolved all of the concerns with my latest commits.

**Comment by radeva** [comment]
run ci

**Comment by radeva** [comment]
run ci

**Review by lini — APPROVED** [review]

**Pull request merged**
