### PR TITLE
Allow imageUri to load local images

### PR DESCRIPTION
**Pull request by triniwiz**

### CODE REVIEW

**Comment by Daxito** [comment]
@triniwiz is it possible to add this other condition as well? I have this image but I know the full path already and this image is not at the Root folder, so we just need to remove the "~"

`} else if (this.imageUri.startsWith("/")) {
                        uri = android.net.Uri.parse('file:' + this.imageUri);
                    }`

**Comment by triniwiz** [comment]
@Daxito will update :)

**Comment by VladimirAmiorkov** [comment]
@Daxito can you give me an example of the full path you would like to use as `imageUri`, how would this path look like in the XML?

**Comment by Daxito** [comment]
@VladimirAmiorkov 
I have this app that takes pictures or displays pictures using CDN, so I need to display them (with fresco), so when I take a picture using the "nativescript-imagepicker" plugin I get back an ImageSource that then I save in my local storage (I have to save it to my local storage as well) like:

var fs = require("file-system");
var documents = fs.knownFolders.documents();
var folder = documents.getFolder("roofImageCache"); 

var saveToLocal = function (imageSource) {
    let path = fs.path.join(folder.path, 'picture.png');
    return {
        saved: imageSource.saveToFile(path, enumsModule.ImageFormat.png),
        filePath: path
    };
}

What I get back is something like **"/data/0/user/something/something/files/roofImageCache/picture.png"**
My xml looks with no difference between setting Url or local path, sometimes I need to set URL and sometimes local path for some pictures.

 <fresco:FrescoDrawee height="80" width="106" placeholderImageUri="~/images/ph.png" showProgressBar="true" imageUri="{{ resolvedUri }}"/>

**Pull request merged**
